### ISSUE TITLE
Support admin and service roles in add-standard-chain.sh

### ISSUE THREAD

**Issue by zchn** [ethereum-optimism/superchain-registry#149]
The automation in [add-standrd-chain.sh](https://github.com/ethereum-optimism/superchain-registry/blob/77a930120ec63dd50c43483c82b1a0a29939ed27/scripts/add-standard-chain.sh#L62) does not automatically add the following roles to the json file:

```
  "ProxyAdminOwner": "",
  "SystemConfigOwner": "",
  "Guardian": "",
  "Challenger": ""
```

As a result, people get the following errors: https://app.circleci.com/pipelines/github/ethereum-optimism/superchain-registry/1687/workflows/6b7258c4-deeb-499e-8f67-b7a6ef65ea58/jobs/5174?invite=true#step-102-4143_0

add-standard-chain.sh should be extended to automatically add these roles

**Comment by geoknee** [comment]
I notice there are also these addresses https://github.com/ethereum-optimism/superchain-registry/pull/110/files which should potentially also be added to the script.

**Comment by geoknee** [comment]
@zchn do you know if these addresses can be scraped from the optimism monrepo in the same way as the other addresses?

**Comment by mds1** [comment]
We can execute some calls to read this data from the chain based on what we know is already in the deployments directory:
- ProxyAdminOwner: Call e.g. `OptimismPortalProxy.admin()` to get the ProxyAdmin, then `ProxyAdmin.owner()` to get ProxyAdminOwner
- SystemConfigOwner: Call `SystemConfigProxy.owner()`
- Guardian: Call `OptimismPortal.superchainConfig()` to get the SuperchainConfig, then `SuperchainConfig.guardian()` to get the guardian. For bedrock chains (like Mode sepolia) you'd call `OptimismPortal.GUARDIAN()` directly, as there is no SuperchainConfig
- Challenger: `L2OutputOracle.CHALLENGER()` for bedrock chains, `L2OutputOracle.CHALLENGER()` and `L2OutputOracle.challenger()` both work for upgrade 4 (extended pause, op-contracts/v1.2.0) and ugprade 6 (op-contracts/v1.3.0). For Fault proof chains (OP Sepolia), the L2OO is removed and I'm not sure where the challenger role now lives, cc @zchn

**Comment by geoknee** [comment]
Re: reading this information from chain in `add-chain.sh`.

1. We "need" this information to perform checks on it in `CheckSecurityConfigs.s.sol`. But, those checks are actually just reading the information from the chain in the same way. We know that they will pass, unless the output of the script is tampered with or the on chain information changes between running the `add-chain.sh` script and running the test. Is the point of those particular checks in `CheckSecurityConfigs.s.sol` to ensure the newly added addresses are "statically queryable" by consumers of the registry (they don't need to make network requests)?

2. I think we have a goal to only ask contributors to give us minimal information in general, and generate extra data from that minimal data. See https://github.com/ethereum-optimism/security-pod/issues/74, https://github.com/ethereum-optimism/security-pod/issues/75. Putting network calls into `add-chain.sh` seems to be driving in the opposite direction to our goal. But perhaps we need to accept that in the short term and revisit it as part of the longer term refactoring of the repo?

3. We should also consider updating this list of addresses parsed and exported by the Go module:
https://github.com/ethereum-optimism/superchain-registry/blob/4a8560435b4a38dffbf5cc30b6b15eeaae002b1e/superchain/superchain.go#L105-L117

**Comment by mds1** [comment]
1. Yea my understanding is those checks ensure validity and consistency of al the data provided, because of the fact that chains don't currently provide a "minimal set of data" with us auto-generating the rest into output files.
2. I believe you are saying "putting network calls into `add-chain.sh` takes us in the opposite direction of requiring minimal data, because it results in more data being committed by the contributor"? If so, I'd argue we already have a fixed set of required input data for contributors, and new network calls in `add-chain.sh` doesn't expand that, and just makes it easier for contributors to automatically fetch data that's currently missing by default (ProxyAdminOwner / SystemConfigOwner / Guardian / Challenger addresses). But to your point, longer term it may be better to have a clear `input` and `output` split where contributors PR a minimal set of data into `input` and we autogenerate everything needed in output, and run checks against that output data. 
3. If they aren't currently needed by any consumers, my initial reaction is to avoid it because that takes us further from a goal of https://github.com/ethereum-optimism/superchain-registry/issues/36 by giving go consumers more information
