### ISSUE TITLE
SuperchainRegistry: modify repo structure

### ISSUE THREAD

**Issue by geoknee** [ethereum-optimism/superchain-registry#285]
We need a compromise between the current structure, and the one[ suggested in the PRD. ](https://docs.google.com/document/d/13nFUdxksND4BzxRA-OdO6DpL888umoVgy56HikMsNW8/edit#heading=h.emx3tkspnffk)

This is because:
*  The repo already has some of the structures that the proposal has, with slightly different names etc.
*  We are constrained somewhat by what Go allows us to do (in terms of embedding files and so on)
* Some level of nesting is perhaps still desired, since we would like to keep the various superchains (mainnet, sepolia, sepoilia-dev-0) separate 

Here is my proposal: 
* Combine "addresses" and "genesis-system-configs" with top level config file.
*  Use TOML instead of yaml and json. 
* rename "configs" to "chains"

We should do this before early access launch, because after that we expect more chains to be added and it will be good to do this while things are quiet. We may want to close or merge any open PRs before doing this.

**Comment by tessr** [comment]
Thank you @geoknee for putting this proposal together! I agree that it makes sense to find a middle ground between what exists today and what was written up in the PRD. Overall, your proposal sounds good but I have one requested change. Here's the rationale. 

From a Product perspective, the repo structure needs to prioritize two things:

1. The legibility of the chain list (answering the question _who is in the Superchain?_)
2. The legibility of the validation checks (answering the question _how do we define the standard config_?) 

Everything else can be an implementation detail and fit whatever format is easiest to maintain for Eng, but these two things should be stupid-easy to find and understand, even for someone who hasn't spent much time within the repo.

For (1), I think that `superchain/configs/chainList.json` is not easy enough to find today. I'd like to see that file as a top-level file, or maybe under `superchain` directly. If there are technical reasons why this isn't possible, we could put a link at the top of the readme or have some other kind of signpost, but I'd rather just have it front and center. I don't imagine that it will be obvious to look in `configs` for the list of members of the Superchain. 

For (2), I think your proposal is pretty much as legible as it gets! So this looks great to me. I _do_ want to just double check that we're good with governance ratifying a toml file rather than an executable set of tests -- I'll check this over Slack and keep you in the loop.

**Comment by geoknee** [comment]
Thanks @tessr/

1. Happily there won't be any constraints on where to put the chain list file (it's an "output" file)
2. he TOML files I was alluding to above were actually the raw config files themselves. More important for blockspace charters are the standard config declaration TOML files. These _are_ unfortunately location constrained, so these are going to be a little bit buried in the current architecture. I can think about options to improve on that.

**Comment by tessr** [comment]
Great. Let's proceed with this proposal then with the chain list file in the top-level directory. 

As for the tests, that's something that we'll have to confirm with Ben... hoping we can get that ironed out this week.

**Comment by geoknee** [comment]
We should pay attention to the `enhanceYAML` function, which will need to be transcribed to a TOML version

https://github.com/ethereum-optimism/superchain-registry/blob/f31b575842ba232011336d7368d96e273ee05ad6/superchain/superchain.go#L178-L179

**Comment by geoknee** [comment]
To implement this, we can use https://kislyuk.github.io/yq/#

**Comment by geoknee** [comment]
I imagine the "definition of done" for this ticket is that we are using TOML everywhere in the registry except perhaps for a couple of autogenerated JSON files (addresses.json and chainList.json).
I would add to that, that we want to make the TOML files as legible as possible, at least as legible as the current YAML files. So a bit more spacing/comments would definitely help. Possibly even some more nesting/indentation, e.g.  the hardfork times, urls, etc could be in their own table.

Essentially anywhere we are using spaces at the moment to improve legibility, we could/should probably use a TOML table with its own header to achieve that. Will require a bit more work in the marshalling / unmarshalling code but hopefully less code hacking spacing into the TOML.

**Comment by BlocksOnAChain** [comment]
@geoknee this makes sense to me.
@tessr how do you feel about the mentioned DoD from the product angle that @geoknee shared: https://github.com/ethereum-optimism/superchain-registry/issues/285#issuecomment-2223971001?

**Comment by tessr** [comment]
Yes. Just to recap the DoD as concisely as possible: 

* All chain info exists in generated files (`chainList.toml` and `chainList.json`) that sit in the top-level directory. 
* We can use the toml file as the canonical reference for the validation checks, and we will be able to change the test suite itself as long as we don't meaningfully alter their semantics. This is something we agreed on with @ben-chain in the last week of June. 

To add: I wouldn't worry too much about optimizing the formatting of the toml files themselves just yet. Ideally they are quite legible, but I don't think it's worth it to invest a lot of complexity in an information hierarchy and/or formatting. I think we can bring the toml to the community and get feedback -- if it's too hard to read, we can adjust once we hear that feedback.
