### ISSUE TITLE
ensure version check consistency

### ISSUE THREAD

**Issue by tessr** [ethereum-optimism/superchain-registry#745]
In the [Standard Rollup Charter](https://gov.optimism.io/t/season-6-standard-rollup-charter-ratification/8135), we commit to relying on three key TOML files for the substance of our validation checks. They are:

1. Params: https://github.com/ethereum-optimism/superchain-registry/blob/main/validation/standard/standard-config-params-mainnet.toml 
2. Roles: https://github.com/ethereum-optimism/superchain-registry/blob/main/validation/standard/standard-config-roles-mainnet.toml
3. Versions: https://github.com/ethereum-optimism/superchain-registry/blob/main/validation/standard/standard-versions-mainnet.toml 

Our version checks _do_ use `standard-versions-mainnet.toml` to validate the contract versions. However, we also use [`standard-bytecodes.toml`](https://github.com/ethereum-optimism/superchain-registry/blob/main/validation/standard/standard-bytecodes.toml) to confirm that contracts are not only using the correct version number but are also consistent in their implementation. 

We should build some internal validation to ensure consistency between `standard-versions-mainnet.toml` and `standard-bytecodes.toml` (and likely `standard-immutables.toml` as well, since the bytecodes file relies on these immutables).

**Comment by geoknee** [comment]
I believe we aren't using the standard contact _addresses_ for validation at the moment, so that could be the missing piece here. 

Note that it is slightly stricter to require chains to use the _exact_ contract deployment we specify in the TOML files, than it is to require them to be using a contract with identical bytecode.

The standard contract addresses _are_ used in downstream software, e.g. the Holocene upgrade scripts https://github.com/ethereum-optimism/optimism/blob/90f4bec43c1aafc1b80dc29289b3d7f0065ac9d4/packages/contracts-bedrock/scripts/upgrades/holocene/scripts/common.sh#L79

**Comment by geoknee** [comment]
Just adding a bit more detail to the current state of things: 

Essentially for each contract and release, we declare a standard:
* version (semver string)
* address
* bytecode (this is declared as a hash with any immutables masked off, so we store the standard immutables, too, so we can compute the masked bytecode hash of any given candidate contract).

The version and address are `standard-versions-mainnet.toml`
The (masked) bytecode hashes are stored in `standard-bytecodes.toml`
The standard immutables are stores in `standard-immutables.toml`

From a validation perspective, the TOMLs are embedded / bound into the validation/standard package and then used for checks in https://github.com/ethereum-optimism/superchain-registry/blob/main/validation/superchain-version.go. We are currently only validating the version and bytecode.

The standard addresses are not used by the validation checks currently, but are consumed by external apps.
